# Generated by Django 4.2.9 on 2024-01-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=200)),
                ('emp_address', models.CharField(max_length=200)),
                ('hiring_date', models.DateField()),
                ('salary', models.FloatField()),
                ('designation', models.CharField(choices=[('TL', 'Team Lead'), ('Associate', 'Associate'), ('Manager', 'Manager')], max_length=100)),
                ('reporting_manager', models.CharField(choices=[('TL', 'Team Lead'), ('Manager', 'Manager'), ('Owner', 'Owner')], max_length=100)),
            ],
        ),
    ]
