# Generated by Django 4.2.9 on 2024-01-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=250)),
                ('dept_floor', models.CharField(max_length=50)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employee_management')),
            ],
        ),
    ]
