# Generated by Django 4.2.9 on 2024-01-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_department_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Maangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField()),
                ('salary_amt', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.department_management')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employee_management')),
            ],
        ),
    ]
