# Generated by Django 4.2.9 on 2024-01-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_salary_maangement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salary_Maangement',
            new_name='Salary_Management',
        ),
    ]
